In [36]:
import pandas as pd

In [37]:
#задача 2
data = pd.read_csv('power.csv')

In [38]:
filtered_countries = data [ (data['country'] == 'Latvia') | (data['country'] == 'Lithuania') | (data['country'] == 'Estonia')]
filtered_category = filtered_countries[ (filtered_countries['category'] == 4) | (filtered_countries['category'] == 12) | (filtered_countries['category'] == 21)]
filtered_quantity = filtered_category [filtered_category['quantity'] > 0]
filtered_by_year = filtered_quantity[(filtered_quantity['year'] >= 2005) & (filtered_quantity['year'] <= 2010)]
#сумма по всем странам Прибалтики
quantity_sum = filtered_by_year['quantity'].sum()                        
print(f'Суммарное потребление стран Прибалтики категорий 4, 12, 21 за период с 2005 по 2010 года составило: {quantity_sum}')

Суммарное потребление стран Прибалтики категорий 4, 12, 21 за период с 2005 по 2010 года составило: 240580.0

In [39]:
#задача 1(1)
film_ratings = pd.read_csv('ratings.csv')
filtered_film_ratings = film_ratings[film_ratings['rating']==5.0]
filtered_film_ratings.head()

   userId  movieId  rating  timestamp
3       1       47     5.0  964983815
4       1       50     5.0  964982931
6       1      101     5.0  964980868
8       1      151     5.0  964984041
9       1      157     5.0  964984100

In [40]:
final_rating_filter = filtered_film_ratings['movieId'].value_counts()
final_rating_filter.head()

318     153
296     123
356     116
2571    109
260     104
Name: movieId, dtype: int64

In [41]:
my_movies = pd.read_csv('movies.csv')
the_answer = my_movies[my_movies['movieId'] == 318]
the_answer

     movieId                             title       genres
277      318  Shawshank Redemption, The (1994)  Crime|Drama

In [42]:
# Задача 1(2)
ratings = pd.read_csv('ratings.csv')

In [43]:
movies = pd.read_csv('movies.csv')

In [44]:
joined = movies.merge(ratings, on = 'movieId')

In [45]:
joined_sorted = joined [(joined['rating'] == 5.0)]

In [46]:
sorted_title = joined_sorted.groupby('title')['rating'].value_counts().loc[lambda x: x == max(x) ]
sorted_title

title                             rating
Shawshank Redemption, The (1994)  5.0       153
Name: rating, dtype: int64

In [47]:
# Задача 3

In [52]:
page_url = 'https://fortrader.org/quotes'
site_table = pd.read_html(page_url)
site_table

[                           Название   Цена  Изменение  Изменение(%)  Обновлено
 0  EURRUB Курс евро к рублю сегодня  86.95       0.29          0.33        NaN
 1       USDRUB Курс рубля к доллару  73.04       0.18          0.25        NaN,
                               Название    Цена  Изменение  Изменение(%)  \
 0       Нефть Brent Курс нефти сегодня   68.85       0.38          0.55
 1          Нефть WTI Цены на нефть WTI   65.29       0.39          0.60
 2  Природный газ Цена на природный газ    2.55      -0.01         -0.43
 3                                 Кофе  134.50       0.00          0.00
 4                             Кукуруза  556.00       2.60          0.47
 5                                  Соя  403.90      -1.80         -0.44
 6                               Хлопок   87.18       0.26          0.30

    Обновлено
 0        NaN
 1        NaN
 2        NaN
 3        NaN
 4        NaN
 5        NaN
 6        NaN  ,
                            Название   Цена  Изменение  Изменение(%)  Обновлено
 0       Золото Цена золота на бирже  1 740       5.00          0.00        NaN
 1  Серебро Цена на серебро на бирже  25.93       0.00          0.01        NaN
 2         Палладий Цена на Палладий  2 473     -13.00         -1.00        NaN
 3           Платина Цены на платину  1 212      -7.00         -1.00        NaN
 4           Медь Цена меди на бирже   4.11       0.05          1.12        NaN,
                                         Название      Цена  Изменение  \
 0                                  ВТБ Акции ВТБ  0.038755   -0.00001
 1                         Газпром Акции газпрома    234.04    0.02000
 2                            Лукойл Акции Лукойл   6 438.5   -6.50000
 3                        Роснефть Акции Роснефти    571.05   -0.15000
 4                       Сбербанк Акции Сбербанка    292.30   -0.03000
 5           Сургутнефтегаз Акции Сургутнефтегаза    35.925    0.00000
 6                      Норникель Акции Норникель    22 846    0.00000
 7                       Аэрофлот Акции Аерофлота     70.50    0.00000
 8                    Северсталь Акции Северсталь  1 433.20   -2.00000
 9                    Транснефть Акции Транснефть   146 700   50.00000
 10             Ростелеком Курс акций ростелекома    110.68   -0.06000
 11                      РУСАЛ Акции РУСАЛ (RUAL)    45.135   -0.00500
 12      Детский мир iDreamSky Technology Limited    136.38   -0.14000
 13             Петропавловск Акции Петропавловск     26.50   -0.10000
 14                    Алроса Акции АЛРОСА (ALRS)   108.200    0.00000
 15                    Магнит Акции Магнит (MGNT)   5 170.5    0.00000
 16                        НМЛК Акции НЛМК (NLMK)   215.200    0.00000
 17                  М.видео Акции М.видео (MVID)    735.60    0.00000
 18    Газпром нефть Акции "Газпром нефть" (SIBN)    380.95   -0.10000
 19                        НМТП Акции НМТП (NMTP)    7.7650    0.00000
 20            Полиметалл Акции Полиметалл (POLY)  1 526.80   -0.10000
 21        Полюс Золото Акции Полюс Золото (PLZL)  14 216.5    0.00000
 22                  НОВАТЭК Акции НОВАТЭК (NVTK)  1 540.20    0.00000
 23                РусГидро Акции РусГидро (HYDR)    0.8130   -0.00060
 24                Татнефть Акции Татнефть (TATN)    609.70   -0.30000
 25        АФК Система Акции АФК "Система" (AFKS)    35.599   -0.00100
 26                                 МТС Акции МТС    318.05   -0.20000
 27                Башнефть Акции Башнефть (BANE)   1 690.5   -6.00000
 28                    Яндекс Акции Яндекс (YNDX)   5 166.2   -0.40000
 29  X5 Retail Group Акции X5 Retail Group (FIVE)  2 495.00    0.00000
 30                  ФСК ЕЭС Акции ФСК ЕЭС (FEES)   0.21342    0.00000
 31                      Мечел Акции Мечел (MTLR)     70.60   -0.04000
 32                МосБиржа Акции МосБиржа (MOEX)    166.24   -0.12000
 33              Интер РАО Акции Интер РАО (IRAO)      5.23    0.00000
 34              Mail.ru Акции Mail.ru (MAIL, ДР)  1 809.20   -1.00000
 35                        Киви Акции Киви (QIWI)     813.0   -1.50000
 36                  Лента Акции Лента (LNTA, ДР)    258.60    0.00000
 37            Тинькофф Акции Тинькофф (TCSG, др)  4 512.60  -11.40000
 38                        Озон Акции Озон (Ozon)  4 247.50   -2.50000

     Изменение(%)  Обновлено
 0      -0.025796        NaN
 1       0.010000        NaN
 2      -0.100000        NaN
 3      -0.030000        NaN
 4      -0.010000        NaN
 5       0.000000        NaN
 6       0.000000        NaN
 7       0.000000        NaN
 8      -0.140000        NaN
 9       0.000000        NaN
 10     -0.050000        NaN
 11     -0.011000        NaN
 12     -0.100000        NaN
 13     -0.380000        NaN
 14      0.000000        NaN
 15      0.000000        NaN
 16      0.000000        NaN
 17      0.000000        NaN
 18     -0.030000        NaN
 19      0.000000        NaN
 20     -0.010000        NaN
 21      0.000000        NaN
 22      0.000000        NaN
 23     -0.073700        NaN
 24     -0.050000        NaN
 25     -0.003000        NaN
 26     -0.060000        NaN
 27     -0.400000        NaN
 28     -0.000000        NaN
 29      0.000000        NaN
 30      0.000000        NaN
 31     -0.060000        NaN
 32     -0.070000        NaN
 33      0.010000        NaN
 34     -0.060000        NaN
 35     -0.200000        NaN
 36      0.000000        NaN
 37     -0.250000        NaN
 38     -0.060000        NaN  ,
                                Название      Цена  Изменение  Изменение(%)  \
 0           Google Акции Google (GOOGL)  2 078.00      -5.89         -0.28
 1                   IBM Акции IBM (IBM)    128.00      -0.24         -0.19
 2     Microsoft Акции Майкрософт (MSFT)    237.79       0.08          0.03
 3              Apple Акции Apple (AAPL)    125.33      -0.24         -0.19
 4                  Yandex Акции яндекса     69.10      -1.81         -2.55
 5                   Toyota Акции Тойоты    152.05      -0.05         -0.03
 6      Volkswagen Курс акций Volkswagen    207.40       0.30          0.14
 7            Amazon Акции Amazon (AMZN)  3 087.40      -4.46         -0.14
 8           Boeing Акции Boeing Company    254.88      -0.33         -0.13
 9              Intel Акции Intel (INTC)     64.83       0.05          0.08
 10            Coca-Cola Акции Coca-Cola     51.23       0.01          0.02
 11         Netflix Акции Netflix (NFLX)    523.41      -0.62         -0.12
 12            Pfizer Акции Pfizer (PFE)     35.81      -0.02         -0.06
 13                        AMD Акции AMD     83.08       0.33          0.40
 14  Walt Disney Акции Walt Disney (DIS)    193.80      -0.44         -0.23
 15           NVIDIA Акции NVIDIA (NVDA)    531.20      -0.45         -0.08
 16           PayPal Акции PayPal (PYPL)    249.00      -0.31         -0.12
 17         Facebook Акции Facebook (FB)    279.81       0.53          0.19
 18             Tesla Акции Тесла (TSLA)    672.10      -4.78         -0.71
 19            Twiter Цена акций твитера     69.05      -0.20         -0.29
 20    Hasbro Цена на акции Hasbro, Inc.     94.70      -2.71         -2.78
 21                               Сименс    135.22      -0.16         -0.12
 22                                 Qiwi     10.88      -0.30         -2.68
 23     Mastercard Акции Mastercard (МА)    382.01      -0.37         -0.10
 24         Moderna Акции Модерна (MRNA)    154.71      -1.31         -0.84
 25        Макдональдс Акции Макдональдс    219.50      -0.36         -0.16
 26                                 MSCI    400.00     -16.58         -3.98
 27                             FIXPRICE      9.65       0.00          0.00
 28                 Zoom Акции Zoom (ZM)    335.80       0.72          0.21
 29     HeadHunter Акции HeadHunter (HH)     20.00     -14.01        -41.19

     Обновлено
 0         NaN
 1         NaN
 2         NaN
 3         NaN
 4         NaN
 5         NaN
 6         NaN
 7         NaN
 8         NaN
 9         NaN
 10        NaN
 11        NaN
 12        NaN
 13        NaN
 14        NaN
 15        NaN
 16        NaN
 17        NaN
 18        NaN
 19        NaN
 20        NaN
 21        NaN
 22        NaN
 23        NaN
 24        NaN
 25        NaN
 26        NaN
 27        NaN
 28        NaN
 29        NaN  ,
                                          Название       Цена  Изменение  \
 0         Индекс МосБиржи Индекс МосБиржи (IMOEX)    357 375      800.0
 1                    Индекс РТС Индекс РТС (RTSI)   1 552.81        0.0
 2                      Dow Jones Индекс Dow Jones  32 825.90        0.0
 3                          S&P 500 Индекс S&P 500      3 955        0.0
 4                    Nasdaq 100 Индекс Nasdaq 100  13 152.30        0.0
 5   Euro Stoxx 50 Индекс Euro Stoxx 50 (STOXX50E)    3 849.7        0.3
 6                            FTSE 100 Индекс FTSE   6 803.61        0.0
 7             Nikkei 225 Индекс Nikkei 225 (N225)     29 885       70.0
 8                Russell 2000 Индекс Russell 2000   2 147.42        0.0
 9                              DAX30 Индекс DAX30   14 506.0      -13.1
 10                           CAC 40 Индекс CAC 40    6 050.1        0.5
 11                         IBEX 35 Индекс IBEX 35    8 636.6        0.0
 12                         ASX 200 Индекс ASX 200    6 798.6        6.0
 13        Фьючерс РТС Курс фьючерса на индекс РТС    152 750      160.0

     Изменение(%)  Обновлено
 0            0.0        NaN
 1            0.0        NaN
 2            0.0        NaN
 3            0.0        NaN
 4            0.0        NaN
 5            0.0        NaN
 6            0.0        NaN
 7            0.0        NaN
 8            0.0        NaN
 9           -0.1        NaN
 10           0.0        NaN
 11           0.0        NaN
 12           0.1        NaN
 13           0.0        NaN  ,
                                            Название       Цена  Изменение  \
 0                         EUR/USD Евро / Доллар США    1.19042    0.00023
 1                         GBP/USD Фунт / Доллар США    1.38940   -0.00079
 2                            USD/CHF Доллар / Франк    0.92544    0.00047
 3                         USD/JPY Доллар США / Иена  109.11300    0.08500
 4                             USD/CNH Доллар / Юань    6.49850    0.00070
 5             USD/CAD Доллар США / Канадский доллар    1.24492    0.00063
 6         AUD/USD Австралийский доллар / Доллар США    0.77352   -0.00106
 7                              EUR/CHF Евро / Франк    1.10170    0.00083
 8   AUD/CAD Австралийский доллар / Канадский доллар    0.96298   -0.00084
 9                      EUR/JPY Евро / Японская йена  129.89300    0.12500
 10                              EUR/GBP Евро / Фунт    0.85662    0.00052
 11                              GBP/JPY Фунт / Йена  151.59600    0.02400
 12            NZDUSD New Zealand Dollar / US Dollar    0.71820   -0.00107

     Изменение(%)  Обновлено
 0        0.01932        NaN
 1       -0.05683        NaN
 2        0.05081        NaN
 3        0.07800        NaN
 4        0.01080        NaN
 5        0.05063        NaN
 6       -0.13685        NaN
 7        0.07539        NaN
 8       -0.08715        NaN
 9        0.09600        NaN
 10       0.06074        NaN
 11       0.01600        NaN
 12      -0.14876        NaN  ,
                                              Название       Цена   Изменение  \
 0                               Bitcoin Курс биткоина  56 090.90 -793.900000
 1          Litecoin Курс лайткоин к доллару (LTC/USD)     198.96   -2.620000
 2   BitcoinCash Курс Биткоин кеш к доллару США (BC...     524.76   -3.650000
 3                                           Dash Dash     227.76    4.140000
 4                                       Ripple Ripple    0.46825    0.007660
 5                                   Ethereum Ethereum   1 779.71  -24.770000
 6                                         Zcash (ZEC)     137.79   -1.530000
 7                                           NEO (NEO)     41.526    0.718000
 8                                           EOS (EOS)     3.9987   -0.066600
 9                                          TRON (TRX)   0.055205    0.002886
 10                                             Monero      234.9    5.200000
 11                                               IOTA     1.3446    0.010100
 12                       ETC/USD эфириум классик, ETC     12.125   -0.293000

     Изменение(%)  Обновлено
 0       -1.40000        NaN
 1       -1.30000        NaN
 2       -0.69000        NaN
 3        1.85000        NaN
 4        1.66308        NaN
 5       -1.37000        NaN
 6       -1.10000        NaN
 7        1.75900        NaN
 8       -1.63830        NaN
 9        5.51616        NaN
 10       2.30000        NaN
 11       0.75680        NaN
 12      -2.35900        NaN  ]

In [54]:
page_url2 = 'https://www.finanz.ru/valyuty/v-realnom-vremeni'

In [56]:
site_table2 = pd.read_html(page_url2, encoding = 'utf-8')
site_table2

[     0       1      2        3       4      5        6       7      8   \
 0  ММВБ   3 590   0,2%   Nasdaq  13 472   0,1%  Биткойн  55 710  -1,8%
 1   РТС   1 553   0,6%   S&P500   3 963  -0,2%    Нефть     682  -0,3%
 2   Dow  32 826  -0,4%  FTSE100   6 804   0,8%   Золото   1 735   0,2%

         9       10    11
 0  USD/RUB  730370  0,2%
 1  EUR/RUB  869065  0,2%
 2  EUR/USD   11901  0,0%  ,
     Unnamed: 0              Рубль  Предложение  Спрос  Предыдущее закрытие  \
 0          NaN            GBP/RUB      1015023      -              1012929
 1          NaN            EUR/RUB       869767      -               867560
 2          NaN            USD/RUB       730630      -               728884
 3          NaN            JPY/RUB        06695      -                06687
 4          NaN            CNY/RUB       112396      -               112034
 5          NaN            CHF/RUB       789238      -               788152
 6          NaN               Евро  Предложение  Спрос  Предыдущее закрытие
 7          NaN            EUR/USD        11906      -                11903
 8          NaN            EUR/GBP        08569      -                08567
 9          NaN            EUR/JPY      1299060      -              1297300
 10         NaN            EUR/CHF        11021      -                11008
 11         NaN         Доллар США  Предложение  Спрос  Предыдущее закрытие
 12         NaN            USD/EUR        08400      -                08401
 13         NaN            USD/GBP        07199      -                07196
 14         NaN            USD/JPY      1091300      -              1090030
 15         NaN            USD/CHF        09258      -                09247
 16         NaN      Японская иена  Предложение  Спрос  Предыдущее закрытие
 17         NaN    JPY/EUR (100:1)        07700      -                07700
 18         NaN            JPY/GBP        00066      -                00066
 19         NaN            JPY/USD        00092      -                00092
 20         NaN    JPY/CHF (100:1)        08500      -                08500
 21         NaN    Фунт стерлингов  Предложение  Спрос  Предыдущее закрытие
 22         NaN            GBP/USD        13891      -                13898
 23         NaN            GBP/JPY      1516115      -              1514787
 24         NaN            GBP/EUR        11670      -                11676
 25         NaN            GBP/CHF        12860      -                12852
 26         NaN  Швейцарский франк  Предложение  Спрос  Предыдущее закрытие
 27         NaN            GBP/CHF        12860      -                12852
 28         NaN            EUR/CHF        11021      -                11008
 29         NaN    JPY/CHF (100:1)        08500      -                08500
 30         NaN            USD/CHF        09258      -                09247
 31         NaN  Украинская гривна  Предложение  Спрос  Предыдущее закрытие
 32         NaN            EUR/UAH       329902      -               329846
 33         NaN            USD/UAH       277100      -               277100
 34         NaN            CHF/UAH       299374      -               299632
 35         NaN            GBP/UAH       384975      -               385086

           %  Абсолютное значение     Время
 0    0,21 %                02094  09:20:00
 1    0,25 %                02207  09:20:00
 2    0,24 %                01746  09:20:00
 3    0,12 %                00008  09:20:00
 4    0,32 %                00362  09:19:00
 5    0,14 %                01085  09:20:00
 6         %  Абсолютное значение     Время
 7    0,03 %                00003  09:20:00
 8    0,03 %                00003  09:20:00
 9    0,14 %                01760  09:20:00
 10   0,12 %                00013  09:20:00
 11        %  Абсолютное значение     Время
 12  -0,02 %               -00001  09:20:00
 13   0,04 %                00003  09:20:00
 14   0,12 %                01270  09:20:00
 15   0,11 %                00011  09:20:00
 16        %  Абсолютное значение     Время
 17  -0,12 %                00000  09:20:00
 18  -0,09 %                00000  09:20:00
 19  -0,12 %                00000  09:20:00
 20  -0,02 %                00000  09:20:00
 21        %  Абсолютное значение     Время
 22  -0,05 %               -00008  09:20:00
 23   0,09 %                01328  09:20:00
 24  -0,05 %               -00006  09:19:00
 25   0,07 %                00009  09:20:00
 26        %  Абсолютное значение     Время
 27   0,07 %                00009  09:20:00
 28   0,12 %                00013  09:20:00
 29  -0,02 %                00000  09:20:00
 30   0,11 %                00011  09:20:00
 31        %  Абсолютное значение     Время
 32   0,02 %                00055  09:20:00
 33   0,00 %                00000  09:19:00
 34  -0,09 %               -00259  09:19:00
 35  -0,03 %               -00111  09:20:00  ,
                                                    0  \
 0                                      Имя и фамилия
 1                                            Телефон
 2                                                NaN
 3  Я даю согласие на обработку своих персональных...

                                                    1  \
 0                                              Город
 1                                              Email
 2                                                NaN
 3  Я даю согласие на обработку своих персональных...

                                                    2  \
 0                                                NaN
 1                                                NaN
 2  Спасибо! Ваша заявка отправлена Финансовый кон...
 3                                                NaN

                                                    3  \
 0                                                NaN
 1                                                NaN
 2  Спасибо! Ваша заявка отправлена Финансовый кон...
 3                                                NaN

                                                    4  \
 0                                                NaN
 1                                                NaN
 2  ошибка: не удалось создать заявку в журнале за...
 3                                                NaN

                                                    5                       6  \
 0                                                NaN                     NaN
 1                                                NaN                     NaN
 2  ошибка: не удалось создать заявку в журнале за...  ошибка: не POST-запрос
 3                                                NaN                     NaN

                         7                                                  8  \
 0                     NaN                                                NaN
 1                     NaN                                                NaN
 2  ошибка: не POST-запрос  Просим Вас согласиться на передачу и обработку...
 3                     NaN                                                NaN

                                                    9
 0                                                NaN
 1                                                NaN
 2  Просим Вас согласиться на передачу и обработку...
 3                                                NaN  ]